rewrite to use a base value, env, and file versions

diff --git a/bin/aws-secrets-send b/bin/aws-secrets-send
--- a/bin/aws-secrets-send
+++ b/bin/aws-secrets-send
@@ -7,17 +7,33 @@ die() {
     echo "$@"
     exit
 }
+
+which aws >/dev/null || die "aws-cli not found."
+
+major=`aws --version 2>&1 | awk '{print $1}' | sed 's|aws-cli/1.\([0-9]*\).*$|\1|'`
+[ ! -z "$major" ] && [ $major -lt 8 ] && die "aws-cli version needs to be >= 1.8."
+
 app=$1
+
 secrets_file=$2
-[ -z "$app" ] && die "Missing app.  Usage: $0 <app> <filename>";
-[ -z "$secrets_file" ] && die "Missing filename.  Usage: $0 <app> <filename>";
+
+env=$APP_ENV
+[ -z "$env" ] && env=$3
+[ -z "$env" ] && env="development"
+
+base=$AWS_SECRETS_BASE
+[ -z "$base" ] && base=$4
+[ -z "$base" ] && base=$app
+
+[ -z "$secrets_file" ] && die "Missing filename.  Usage: $0 <app> <?filename|.env> <?env|development> <?base|app>";
+[ -z "$app" ] && die "Missing app name.  Usage: $0 <app> <?filename|.env> <?env|development> <?base|app>";
 
 src=$secrets_file
-s3_bucket=$app-secrets
-s3_key=$app-aws-secrets
-kms_alias=$app-secrets
+kms_alias=$base-secrets
+s3_bucket=$base-secrets
+s3_key=$app/$env/secrets
 
-tmp=`mktemp -d`
+tmp=`mktemp -d 2>/dev/null || mktemp -d -t 'astmpdir'`
 encrypted=$tmp/data.enc
 
 key_id=`aws kms list-aliases --output text --query "Aliases[?AliasName=='alias/$kms_alias'].TargetKeyId | [0]"`
@@ -30,13 +46,15 @@ aws kms encrypt \
     | base64 --decode \
     > $encrypted
 
-aws s3api put-object \
+version_id=`aws s3api put-object \
     --bucket $s3_bucket \
     --key $s3_key \
     --acl private \
     --body $encrypted \
     --output text \
-    --query 'None' \
-    | egrep -v '^None$' || true
+    --query 'VersionId'`
 
 rm -rf $tmp
+
+# Print out the file and version id
+echo "{ \"file\": \"s3://$s3_bucket/$s3_key\", \"versionId\": \"$version_id\" }"
